services:
  currencywebsite:
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "5000:8080" 
    depends_on:
      - businessapi
      - dataapi
      - db
      - cache

  businessapi:
    build:
      context: .
      dockerfile: Dockerfile 
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5002:8080"
    command: ["dotnet", "/app/publish/businessapi/BusinessAPI.dll"]
    depends_on:
      - db

  dataapi:
    build:
      context: .
      dockerfile: Dockerfile  
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5001:8080"
    command: ["dotnet", "/app/publish/dataapi/DataAPI.dll"]
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: ExchangeRatesDb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  cache:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - cache-data:/data

volumes:
  db-data:
  cache-data:
